### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by mohashyne** [cancelei/search_engine#8]
# Kindly  check the database design below and see if it matches the structure for this app , because it better for us to have the structure to ease our work and also wireframes for the frontend for make refrence if a member of the team is doing something wrong:

![search_engine_design](https://github.com/cancelei/search_engine/assets/32427719/367d4ae6-ceea-49cb-84d2-57955ab0ae6d)

Relationships:

    One-to-Many (1
    ) Relationships:
        user_profile to user_account: Each user_profile can have one user_account.
        user_profile to search_history: Each user_profile can have many search_history entries.
        search_result to search_history: Each search_result can be associated with multiple search_history entries.

**Comment by mohashyne** [comment]
![search_engine_design](https://github.com/cancelei/search_engine/assets/32427719/90b2906b-3358-469e-ba7e-4bf011a07909)

![Awesome_search_engine](https://github.com/cancelei/search_engine/assets/32427719/ccca3064-2530-4bfe-82fe-66a9650e5830)

**Comment by cancelei** [comment]
@mohashyne I think your effort is nice!

Before we implement changes, I think it's appropriate for you to work with @Hemit99123 on the Reward system, and implement the PR related to rails MVC to make his front end work. He told me that the front end is ready (but most likely on his local).

Then we also would have a Settings page that @Gabriel-Dalton mentioned before you joined, which would add more fields to the tables.

If I were you, I wouldn't worry about the database design just yet, since things are still solidifying and more features could be necessary with database changes.

**Comment by hemitoncode** [comment]
@mohashyne may I ask what software you used to create the diagram?

**Comment by hemitoncode** [comment]
Also for the rewards program (ecoquest)... I am done frontend, just need to push to GitHub so we can start work on backend.

I will use whatever program @mohashyne for db design :)
